version: "3.8"

services:
  petalframe:
    image: python:3.11-slim
    container_name: petalframe
    working_dir: /app
    command: tail -f /dev/null

    volumes:
      - ./server.py:/app/server.py
      - ./requirements.txt:/app/requirements.txt
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json
    ports:
      - "41873:8000"
    restart: unless-stopped
