version: "3.8"

services:
  petalframe:
    image: petalframe:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petalframe
    ports:
      - "41873:8000"
    restart: unless-stopped
    volumes:
      - petalframe_uploads:/app/uploads
      - petalframe_rooms:/app/user_rooms
      - petalframe_db:/app/app.db

volumes:
  petalframe_uploads:
  petalframe_rooms:
  petalframe_db:
