version: "3.8"

services:
  petalframe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petalframe
    ports:
      - "41873:8000"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./user_rooms:/app/user_rooms
      - ./app.db:/app/app.db
