version: "3.8"

services:
  petalframe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petalframe
    ports:
      - "41873:8000"
    restart: unless-stopped
    volumes:
      - petal_data:/app/data

volumes:
  petal_data:
